### ISSUE TITLE
Question about label_to_npy.py file

### ISSUE THREAD

**Issue by ywssng** [ki4ai-yhs/merc2020#1]
Hello, I have question about label_to_npy.py file.

The results of changing the .csv files to npy file using the updated code (label_to_npy.py), and the already given label npy files from this repository are different.
I think this difference is from the order of the emotions from the list (here. [https://github.com/ki4ai-yhs/merc2020/blob/master/utils/label_to_npy.py#L6](url).

[https://github.com/ki4ai-yhs/merc2020/blob/master/modules/multimodal/features/label_val.npy](url) this gives happy as '0', and
[https://github.com/ki4ai-yhs/merc2020/blob/master/utils/label_to_npy.py](url) gives happy as '3'.

So of those two labels, which label is used for pre-trained model?

**Comment by ki4ai-yhs** [comment]
Thank you for participating in MERC2020.

In pre-trained model, the label was sorted in this way:

['hap', 'ang', 'dis', 'fea', 'neu', 'sad', 'sur']

Thus, I have found the wrong part of what you said in "label_to_npy.py" and
I have corrected it now.

Thank you.

*----------------------------------------------------------------*
*Young Hoon Shin*
Senior Research Scientist / Ph.D.
KAIST Institute for Artificial Intelligence (KI4AI)
Tel: +82-42-350-7094
E-mail: yh.s@kaist.ac.kr


2020년 10월 24일 (토) 오후 2:29, Yeongwoo Song <notifications@github.com>님이 작성:

**Comment by ywssng** [comment]
Thanks!! Changing the issue as closed bb.
